# Generated by Django 4.0.3 on 2022-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
                ('Password', models.TextField(max_length=25)),
                ('Phonenumber', models.TextField(max_length=25)),
                ('Gender', models.TextField(max_length=25)),
            ],
        ),
    ]
